spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/group3?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update